master: test_one.sh: only switch once for each cppad_has_package.

diff --git a/bin/test_one.sh.in b/bin/test_one.sh.in
--- a/bin/test_one.sh.in
+++ b/bin/test_one.sh.in
@@ -9,6 +9,19 @@
 # A copy of this license is included in the COPYING file of this distribution.
 # Please visit http://www.coin-or.org/CppAD/ for information on other licenses.
 # -----------------------------------------------------------------------------
+set_libdir() {
+	if [ -e $1/lib ]
+	then
+		libdir='lib'
+	elif [ -e $1/lib64 ]
+	then
+		libdir='lib64'
+	else
+		echo "bin/test_one.sh: cannot file $1/lib or $1/lib64"
+		exit 1
+	fi
+}
+# -----------------------------------------------------------------------------
 # Command line arguments
 if [ "$0" != 'bin/test_one.sh' ]
 then
@@ -58,9 +71,31 @@ then
 fi
 original_dir=`pwd`
 # ---------------------------------------------------------------------------
-# Make sure cppad_lib is there
+# initialize
+include_flags="-I $original_dir"
+library_flags="-lboost_thread -lpthread"
+#
+# adolc
+if [ @cppad_has_adolc@ == 1 ]
+then
+	include_flags="$include_flags -I @adolc_prefix@/include"
+	#
+	set_libdir @adolc_prefix@
+	library_flags="$library_flags -L@adolc_prefix@/$libdir -ladolc"
+	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:@adolc_prefix@/$libdir"
+fi
+#
+# colpack
 if [ @cppad_has_colpack@ == 1 ]
 then
+	include_flags="$include_flags -I @colpack_prefix@/include"
+	#
+	set_libdir @colpack_prefix@
+	library_flags="$library_flags -L@colpack_prefix@/$libdir -lColPack"
+	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:@colpack_prefix@/$libdir"
+	cppad_lib_path="@PROJECT_BINARY_DIR@/cppad_lib/libcppad_lib.so"
+	library_flags="$library_flags $cppad_lib_path"
+	#
 	if ! ls build/cppad_lib/libcppad_lib.* > /dev/null
 	then
 		cd build
@@ -68,21 +103,17 @@ then
 		cd ..
 	fi
 fi
-# ---------------------------------------------------------------------------
-# include_flags
-include_flags="-I $original_dir"
-if [ @cppad_has_adolc@ == 1 ]
-then
-	include_flags="$include_flags -I @adolc_prefix@/include"
-fi
-if [ @cppad_has_colpack@ == 1 ]
-then
-	include_flags="$include_flags -I @colpack_prefix@/include"
-fi
+#
+# ipopt
 if [ @cppad_has_ipopt@ == 1 ]
 then
 	include_flags="$include_flags -I @ipopt_prefix@/include"
+	#
+	ipopt_flags=`pkg-config --libs ipopt`
+	library_flags="$library_flags $ipopt_flags"
 fi
+#
+# eigen
 if [ @cppad_has_eigen@ == 1 ]
 then
 	include_flags="$include_flags -isystem @eigen_prefix@/include"
@@ -105,25 +136,6 @@ sed < $dir/$main > test_one.cpp \
 #
 # compiler flags
 cxx_flags='@cppad_cxx_flags@'
-#
-# library flags
-library_flags=`pkg-config --libs ipopt`
-library_flags="$library_flags -lboost_thread -lpthread"
-for lib in lib lib64
-do
-	if [ -e @colpack_prefix@/$lib ]
-	then
-		library_flags="$library_flags -L@colpack_prefix@/$lib -lColPack"
-		export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:@colpack_prefix@/$lib"
-		cppad_lib_path="@PROJECT_BINARY_DIR@/cppad_lib/libcppad_lib.so"
-		library_flags="$library_flags $cppad_lib_path"
-	fi
-	if [ -e @adolc_prefix@/$lib ]
-	then
-		library_flags="$library_flags -L@adolc_prefix@/$lib -ladolc"
-		export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:@adolc_prefix@/$lib"
-	fi
-done
 #
 # compile command
 compile_command="@CMAKE_CXX_COMPILER@ test_one.cpp -o test_one.exe
