master: allow for make or test_one in appveyor.sh and travis.sh.

diff --git a/bin/test_one.sh.in b/bin/test_one.sh.in
--- a/bin/test_one.sh.in
+++ b/bin/test_one.sh.in
@@ -59,6 +59,12 @@ extra: extra source files and/or options for the compile command
 EOF
     exit 1
 fi
+if ! echo "$1" | grep '/' > /dev/null
+then
+    echo 'test_one.sh: dir missing in'
+    echo '    bin/test_one.sh dir/file'
+    exit 1
+fi
 dir=`echo $1 | sed -e 's|/[^/]*$||'`
 file=`echo $1 | sed -e 's|.*/||'`
 extra="$2"
