trunk: Heading toward having two vectors of set classes to choose from.
change connection to vector_pack:
check_doxygen.sh, ad_fun.hpp, for_jac_sweep.hpp, load_op.hpp
rev_sparse_jac.hpp, store_op.hpp, rev_sparse_hes.hpp, rev_jac_sweep.hpp,
cond_op.hpp, sparse_binary_op.hpp, sparse_unary_op.hpp

*/test_one.sh.in: detect and report error when file does not exist.
makefile.am: change connection.hpp to vector_set.hpp.
makefile.in: changes automatically generated from change in makefile.am
prototype_op.hpp: notes about changing documentation (to do).
vector_set.hpp: connection->vector_pack, n_from->n_set, n_to->limit
connection.hpp: move to vector_set.hpp.
op.hpp: include vector_set.hpp.



git-svn-id: https://projects.coin-or.org/svn/CppAD/trunk@1524 0e562018-b8fb-0310-a933-ecf073c7c197

diff --git a/example/test_one.sh.in b/example/test_one.sh.in
--- a/example/test_one.sh.in
+++ b/example/test_one.sh.in
@@ -1,6 +1,6 @@
 # $Id$
 # -----------------------------------------------------------------------------
-# CppAD: C++ Algorithmic Differentiation: Copyright (C) 2003-08 Bradley M. Bell
+# CppAD: C++ Algorithmic Differentiation: Copyright (C) 2003-09 Bradley M. Bell
 #
 # CppAD is distributed under multiple licenses. This distribution is under
 # the terms of the 
@@ -15,6 +15,11 @@ then
 	echo "usage: test_one.sh file [extra]"
 	echo "file is the *.cpp file name with extension"
 	echo "and extra is extra options for g++ command"
+	exit 1
+fi
+if [ ! -e "$1" ]
+then
+	echo "Cannot find the file $1"
 	exit 1
 fi
 # determine the function name
diff --git a/test_more/test_one.sh.in b/test_more/test_one.sh.in
--- a/test_more/test_one.sh.in
+++ b/test_more/test_one.sh.in
@@ -18,6 +18,11 @@ then
 	echo "and extra is extra options for g++ command"
 	exit 1
 fi
+if [ ! -e "$1" ]
+then
+	echo "Cannot find the file $1"
+	exit 1
+fi
 fun=`grep "^bool *[a-zA-Z0-9_]*( *void *)" $1 | tail -1 | \
 	sed -e "s/^bool *\([a-zA-Z0-9_]*\) *( *void *)/\1/"`
 if [ -e test_one.exe ]
