Improve documentation and example for ForOne.
SvnCommit: file that made this commit.
Dev.omh: move Developer.omh here.
RevSparseHes.h: fix cross reference to current section.
Jacobian.h: fix cross reference to current section (and other minor edits).
ForOne.h: major changes to doc and make code agree with new notation.
RevSparseJac.h: fix cross reference to current section.
Build: Change Developer directory to Dev directory.
SvnStatus: Change Developer directory to Dev directory.
InstallUnix.omh: Change Developer directory to Dev directory.
WhatsNew06.omh: user's view of the changes.
InstallWindows.omh: Change Developer directory to Dev directory.
CleanCppAD: Change Developer directory to Dev directory.
Jacobian.cpp: minor edit.
ForOne.cpp: make like other examples and ForOne documentation.
Developer.omh: move from here to Dev.omh.
RunOmhelp: use new features of OMhelp to better report warning, errors.
Makefile: Change Developer directory to Dev directory.
----------------------------------------------------------------------
Edit section above for individual cases, section below stays the same
----------------------------------------------------------------------


git-svn-id: https://projects.coin-or.org/svn/CppAD/trunk@379 0e562018-b8fb-0310-a933-ecf073c7c197

diff --git a/RunOMhelp b/RunOMhelp
--- a/RunOMhelp
+++ b/RunOMhelp
@@ -16,25 +16,31 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 # ---------------------------------------------------------------------------
 #
-if [ "$1" != "Doc" ] && [ "$1" != "Developer" ]
+if [ "$1" != "Doc" ] && [ "$1" != "Dev" ]
 then
-	echo "RunOMhelp target: where target is Doc or Developer"
+	echo "RunOMhelp target: where target is Doc or Dev"
 	exit
 fi
-if [ "$1" = Developer ]
+if [ "$1" = Dev ]
 then
-	rm -r -f Developer
+	rm -r -f Dev
 	#
 	echo "Building developer documentation"
-	mkdir Developer
-	cd    Developer
-	if ! omhelp ../Developer.omh -xml -debug > ../RunOMhelp.log
+	mkdir Dev
+	cd    Dev
+	if ! omhelp ../Dev.omh -xml -debug > ../OMhelp.Dev.log
 	then
+		grep "^OMhelp Error:" ../OMhelp.Dev.log
 		echo "OMhelp could not build developer documentation."
+		echo "See the complete error message in OMhelp.Dev.log"
 		exit 1
 	fi
-	omhelp ../Developer.omh -debug
+	omhelp ../Dev.omh -debug
 	cd ..
+	if grep "^OMhelp Warning:" OMhelp.Dev.log
+	then
+		echo "See the complete warning messages in OMhelp.Dev.log."
+	fi
 fi
 if [ "$1" = Doc ]
 then
@@ -44,17 +50,23 @@ then
 	#
 	mkdir Doc
 	cd    Doc
-	if ! omhelp ../Doc.omh > ../RunOMhelp.log \
+	if ! omhelp ../Doc.omh > ../OMhelp.Doc.log \
 		-l http://www.coin-or.org/CppAD/ \
 		-xml \
 		-debug
 	then
+		grep "^OMhelp Error:" ../OMhelp.Dev.log
 		echo "OMhelp could not build user documentation."
+		echo "See the complete error message in OMhelp.Doc.log"
 		exit 1
 	fi
 	omhelp ../Doc.omh  \
                 -l http://www.coin-or.org/CppAD/ \
 		-debug
 	cd ..
+	if grep "^OMhelp Warning:" OMhelp.Doc.log
+	then
+		echo "See the complete warning messages in OMhelp.Doc.log."
+	fi
 fi
 exit 0
